services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: fraud
    volumes:
      - ./postgres_data:/var/lib/postgresql/data  # Persist database data

  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - "8080:8080"

  streamlit:
    build: .
    restart: always
    depends_on:
      - database
    ports:
      - "8501:8501"
    volumes:
      - ./src/app:/app/src/app  # Mount only the app directory
    environment:
      - DATABASE_URL=postgresql://docker:docker@database:5432/fraud
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
